version: '3.8'

services:
  #----------------------------------------#
  #--------|Nginx and Letsencrypt|---------#
  #----------------------------------------#

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    depends_on:
      - client-ui
      - gateway
      - employee-ui
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./data/certs:/etc/nginx/certs
      - ./data/vhost.d:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
    environment:
      - ENABLE_IPV6=true
    networks:
      - default
      - nginx-net

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/certs:/etc/nginx/certs
      - ./data/vhost.d:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    networks:
      - default
      - nginx-net

  #-----------------------------------------#
  #---------------|Frontends|---------------#
  #-----------------------------------------#

  client-ui:
    build:
      context: ./Internet-Bank-Client
    container_name: client-ui
    hostname: client-ui
    expose:
      - "5000"
    env_file:
      - ./Internet-Bank-Client/.env
    depends_on:
      - gateway
    networks:
      - nginx-net
      - gateway-net

  employee-ui:
    build:
      context: ./Internet-Bank-Employee
    container_name: employee-ui
    hostname: employee-ui
    expose:
      - "5001"
    env_file:
      - ./Internet-Bank-Employee/.env
    depends_on:
      - gateway
    networks:
      - nginx-net
      - gateway-net

  #-----------------------------------------#
  #-------------|API Gateway|---------------#
  #-----------------------------------------#

  gateway:
    build:
      context: ./bank-gateway-api
    container_name: gateway
    hostname: gateway
    depends_on:
      - user-service
      - account-service
      - credit-service
#    ports:
#      - "7733:7733"  # Временно
    expose:
      - "7733"
    env_file:
      - ./bank-gateway-api/.env
    networks:
#      - default  # Временно
      - nginx-net
      - gateway-net
      - rabbit-account-net

  #-----------------------------------------#
  #---------------|Backends|----------------#
  #-----------------------------------------#

  user-service:
    build:
      context: ./user-microservice-rust
    container_name: user-service
    hostname: user-service
    depends_on:
      - user-db
    expose:
      - "2288"
    # ports:
    #   - "2288:2288"  # Временно
    env_file:
      - ./user-microservice-rust/.env
    networks:
      # - default # Временно
      - gateway-net
      - user-db-net

  account-service:
    build:
      context: ./account-microservice
    container_name: account-service
    hostname: account-service
    depends_on:
      - account-db
      - exchange-service
    expose:
      - "2289"
#    ports:
 #     - "2289:2289"  # Временно
    env_file:
      - ./account-microservice/.env
    networks:
#      - default # Временно
      - gateway-net
      - rabbit-net
      - account-db-net
      - exchange-net
      - rabbit-account-net

  credit-service:
    build:
      context: ./credit_service
    container_name: credit-service
    hostname: credit-service
    depends_on:
      - credit-db
    expose:
      - "2290"
    # ports:
    #   - "2290:2290"  # Временно
    env_file:
      - ./credit_service/.env
    networks:
      # - default # Временно
      - gateway-net
      - rabbit-net
      - credit-db-net

  exchange-service:
    build:
      context: ./exchange-service
    container_name: exchange-service
    hostname: exchange-service
    expose:
      - "2291"
    # ports:
    #   - "2290:2290"  # Временно
    env_file:
      - ./credit_service/.env
    networks:
      - default
      - gateway-net
      - exchange-net

  #-----------------------------------------#
  #---------------|Storages|----------------#
  #-----------------------------------------#

  user-db:
    image: postgres:15
    container_name: user-db
    hostname: user-db
    restart: always
    env_file:
      - ./user-microservice-rust/.env
    expose:
      - "5433"
    networks:
      - user-db-net
    volumes:
      - user_data:/var/lib/postgresql/data
    command: ["-p", "5433"]

  account-db:
    image: postgres:15
    container_name: account-db
    hostname: account-db
    restart: always
    env_file:
      - ./account-microservice/.env
    expose:
      - "5434"
#    ports:
#      - "5434:5434" # Временно
    networks:
#      - default # Временно
      - account-db-net
    volumes:
      - account_data:/var/lib/postgresql/data
    command: [ "-p", "5434" ]

  credit-db:
    image: postgres:15
    container_name: credit-db
    hostname: credit-db
    restart: always
    env_file:
      - ./credit_service/.env
    expose:
      - "5435"
    networks:
      - credit-db-net
    volumes:
      - credit_data:/var/lib/postgresql/data
    command: [ "-p", "5435" ]

  #-----------------------------------------#
  #-----------|Message brokers|-------------#
  #-----------------------------------------#

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    env_file:
      - ./.env.rabbit
    expose:
      - "5672"
      - "15672:15672"
#    ports:
#      - "5672:5672"  # Временно
#      - "15672:15672"
    networks:
#      - default # Временно
      - rabbit-net

  rabbitmq-account:
    image: rabbitmq:3-management
    container_name: rabbitmq-account
    hostname: rabbitmq-account
    restart: always
    env_file:
      - ./.env.rabbit.account
    # expose:
    #   - "5673"
    #   - "15673:15673"
    ports:
      - "5673:5673"  # Временно
      - "15673:15673"
    volumes:
      - ./account-rabbit.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - default # Временно
      - rabbit-account-net

  #----------------------------------------#
  #----------------------------------------#
  #----------------------------------------#

networks:
  nginx-net:
    internal: True
  gateway-net:
    internal: True
  user-db-net:
    internal: True
  rabbit-net:
    internal: True
  rabbit-account-net:
    internal: True
  account-db-net:
    internal: True
  credit-db-net:
    internal: True
  exchange-net:
    internal: True

volumes:
  user_data:
  account_data:
  credit_data:
