version: '3.8'

services:
  #----------------------------------------#
  #--------|Nginx and Letsencrypt|---------#
  #----------------------------------------#

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    depends_on:
      - client-ui
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./data/certs:/etc/nginx/certs
      - ./data/vhost.d:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
    environment:
      - ENABLE_IPV6=true
    networks:
      - default
      - nginx-net

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/certs:/etc/nginx/certs
      - ./data/vhost.d:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    networks:
      - default
      - nginx-net

  #-----------------------------------------#
  #---------------|Frontends|---------------#
  #-----------------------------------------#

  client-ui:
    build:
      context: ./Internet-Bank-Client
    container_name: client-ui
    hostname: client-ui
    expose:
      - "5000"
    env_file:
      - ./Internet-Bank-Client/.env
    depends_on:
      - gateway
    networks:
      - nginx-net
      - gateway-net

  #-----------------------------------------#
  #-------------|API Gateway|---------------#
  #-----------------------------------------#

  gateway:
    build:
      context: ./bank-gateway-api
    container_name: gateway
    hostname: gateway
    depends_on:
      - user-service
    expose:
      - "8000"
    env_file:
      - ./bank-gateway-api/.env
    networks:
      - gateway-net

  #-----------------------------------------#
  #---------------|Backends|----------------#
  #-----------------------------------------#

  user-service:
    build:
      context: ./user-microservice-rust
    container_name: user-service
    hostname: user-service
    depends_on:
      - user-db
    expose:
      - "2288"
    env_file:
      - ./user-microservice-rust/.env
    networks:
      - gateway-net
      - user-db-net

  #-----------------------------------------#
  #---------------|Storages|----------------#
  #-----------------------------------------#

  user-db:
    image: postgres:15
    container_name: user-db
    hostname: user-db
    restart: always
    env_file:
      - ./user-microservice-rust/.env
    expose:
      - "5433"
    networks:
      - user-db-net
    volumes:
      - user_data:/var/lib/postgresql/data
    command: ["-p", "5433"]

  #-----------------------------------------#
  #-----------|Message brokers|-------------#
  #-----------------------------------------#

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    env_file:
      - ./.env.rabbit
    expose:
      - "5672"
    ports:
      - "15672:15672"
    networks:
      - rabbit-net
      - nginx-net

  #----------------------------------------#
  #----------------------------------------#
  #----------------------------------------#

networks:
  nginx-net:
    internal: True
  gateway-net:
    internal: True
  user-db-net:
    internal: True
  rabbit-net:
    internal: True

volumes:
  user_data:
